import { Category, ContentItem } from './types';

export const BURSA_CONTENT: ContentItem[] = [
  {
    id: 1,
    title: "Paleolitik Çağ & Aktopraklık",
    description: "Bursa'da yaşamın izleri 8500 yıl öncesine uzanır. Aktopraklık Höyüğü, Avrupa'nın ilk çiftçilerine ev sahipliği yapmış, yerleşik hayata geçişin en net kanıtıdır.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCrfKnQydeMFbb5wtXbp44ZtmRArEBhRFpwA&s",
    category: Category.HISTORY,
    bgColor: "bg-stone-100",
    textColor: "text-stone-800",
    badgeColor: "bg-stone-200",
    lat: 40.160163,
    lng: 28.795891
  },
  {
    id: 2,
    title: "İznik (Nicaea)",
    description: "Roma, Bizans, Selçuklu ve Osmanlı'ya başkentlik yapmış kadim şehir. Çinileriyle dünyayı süsleyen İznik, tarihin dört büyük imparatorluğunun izlerini taşır.",
    imageUrl: "https://iznik.bel.tr/public/uploads/images/pages/original/1733341456_a8c746c508864bbd039c.jpeg",
    category: Category.HISTORY,
    bgColor: "bg-blue-50",
    textColor: "text-blue-900",
    badgeColor: "bg-blue-200",
    lat: 40.4284,
    lng: 29.7201
  },
  {
    id: 3,
    title: "Tophane: Osman & Orhan Gazi",
    description: "Osmanlı Devleti'nin kurucuları burada, Bursa'yı kuş bakışı izler. Tophane yamaçları, bir cihan imparatorluğunun doğuşuna şahitlik eden manevi bir duraktır.",
    imageUrl: "https://media-cdn.tripadvisor.com/media/photo-s/17/0c/08/36/osmangazi-orhangazi-turbesi.jpg",
    category: Category.HISTORY,
    bgColor: "bg-amber-50",
    textColor: "text-amber-900",
    badgeColor: "bg-amber-200",
    lat: 40.1856,
    lng: 29.0581
  },
  {
    id: 4,
    title: "Ulu Cami",
    description: "Bursa'nın Ayasofya'sı olarak bilinir. 20 kubbesiyle İslam mimarisinin zirvesi, içindeki şadırvanı ve hat sanatlarıyla taşın duaya dönüştüğü yerdir.",
    imageUrl: "https://www.kulturportali.gov.tr/contents/images/Bursa%20Ulu%20Camii%20Murat%20%c3%96CAL%20(24).JPG",
    category: Category.CULTURE,
    bgColor: "bg-emerald-50",
    textColor: "text-emerald-900",
    badgeColor: "bg-emerald-200",
    lat: 40.1835,
    lng: 29.0617
  },
  {
    id: 5,
    title: "Muradiye Külliyesi",
    description: "Osmanlı sultanlarının son uykularına yattığı huzurlu bahçe. II. Murad'ın ruhunu yansıtan bu külliye, şehrin manevi sükunet noktasıdır.",
    imageUrl: "https://belediye-assets.s3.eu-central-1.amazonaws.com/public/files/places/images/6859848139aaa.webp",
    category: Category.HISTORY,
    bgColor: "bg-teal-50",
    textColor: "text-teal-900",
    badgeColor: "bg-teal-200",
    lat: 40.1895,
    lng: 29.0467
  },
  {
    id: 6,
    title: "Emir Sultan",
    description: "Bursa'nın manevi mimarı, gönüllerin sultanı. Erguvan fasıllarının doğduğu bu tepe, şehrin en önemli ziyaretgahlarından biridir.",
    imageUrl: "https://belediye-assets.s3.eu-central-1.amazonaws.com/public/files/places/images/684c2a308c7d4.webp",
    category: Category.CULTURE,
    bgColor: "bg-rose-50",
    textColor: "text-rose-900",
    badgeColor: "bg-rose-200",
    lat: 40.1818,
    lng: 29.0805
  },
  {
    id: 7,
    title: "Karagöz & Hacivat",
    description: "Gölge oyununun efsanevi ikilisi Bursa'da doğdu. Perde arkasındaki atışmaları yüzyıllardır hem güldürür hem düşündürür.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Turchia%2C_marionette_karagoz%2C_xx_secolo%2C_karag%C3%B6z_e_hacivat_%28protagonista_e_antagonista%29_02.jpg/960px-Turchia%2C_marionette_karagoz%2C_xx_secolo%2C_karag%C3%B6z_e_hacivat_%28protagonista_e_antagonista%29_02.jpg",
    category: Category.CULTURE,
    bgColor: "bg-purple-50",
    textColor: "text-purple-900",
    badgeColor: "bg-purple-200",
    lat: 40.1982, 
    lng: 29.0336 // Karagoz Museum
  },
  {
    id: 8,
    title: "Irgandı Köprüsü",
    description: "Dünyada üzerinde çarşı bulunan dört köprüden biri. Zanaatkarların el emeği ürünleri, derenin sesi eşliğinde sanatseverlerle buluşur.",
    imageUrl: "https://medyahataycom.teimg.com/crop/1280x720/medyahatay-com/uploads/2023/07/agency/igf/bursada-tarihi-irgandi-koprusu-hakkinda-bilmedikleriniz.jpg",
    category: Category.CULTURE,
    bgColor: "bg-orange-50",
    textColor: "text-orange-900",
    badgeColor: "bg-orange-200",
    lat: 40.1815,
    lng: 29.0697
  },
  {
    id: 9,
    title: "Koza Han & İpek Yolu",
    description: "İpek Yolu'nun son durağı. Asırlık çınarların altında ipek kumaşların hışırtısı ve kahve kokusu birbirine karışır.",
    imageUrl: "https://cdnuploads.aa.com.tr/uploads/userFiles/caec1b32-8257-4f58-87b0-6657c62b92b3/New%20folder%20(8)%2Fkozahan1.jpg",
    category: Category.HISTORY,
    bgColor: "bg-yellow-50",
    textColor: "text-yellow-900",
    badgeColor: "bg-yellow-200",
    lat: 40.1843,
    lng: 29.0626
  },
  {
    id: 10,
    title: "Uludağ (Olympos)",
    description: "Antik çağın Olympos'u, günümüzün kış turizmi merkezi. Zirvesindeki karı ve eteklerindeki yeşiliyle Bursa'nın heybetli koruyucusudur.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVvazdekagH-IzFGBE4k0hlf9UVMlcAtSAvA&s",
    category: Category.NATURE,
    bgColor: "bg-cyan-50",
    textColor: "text-cyan-900",
    badgeColor: "bg-cyan-200",
    lat: 40.0700,
    lng: 29.2200
  },
  {
    id: 11,
    title: "Tarihi Çekirge Kaplıcaları",
    description: "Roma döneminden beri şifa dağıtan sular. Bursa'nın termal zenginliği, Çekirge semtindeki tarihi hamamlarla vücut bulur.",
    imageUrl: "https://www.kulturportali.gov.tr/repoKulturPortali/large/30042013/e6151b14-8867-48cd-bf8a-58f20d90e76f.jpg?format=jpg&quality=50",
    category: Category.NATURE,
    bgColor: "bg-sky-50",
    textColor: "text-sky-900",
    badgeColor: "bg-sky-200",
    lat: 40.1983,
    lng: 29.0336
  },
  {
    id: 12,
    title: "Cumalıkızık & UNESCO",
    description: "700 yıllık Osmanlı sivil mimarisinin yaşayan örneği. Rengarenk evleri, dar sokakları ve köy kahvaltısıyla zamanın durduğu yer.",
    imageUrl: "https://www.bizevdeyokuz.com/wp-content/uploads/Cumalikizik-renkli-evler.jpg",
    category: Category.CULTURE,
    bgColor: "bg-indigo-50",
    textColor: "text-indigo-900",
    badgeColor: "bg-indigo-200",
    lat: 40.1755,
    lng: 29.1706
  },
  {
    id: 13,
    title: "İnkaya Çınarı",
    description: "600 yılı aşkın süredir tarihe tanıklık eden dev bir çınar. Gölgesinde çay içmek, Bursa'nın huzurunu solumaktır.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM9jQVoSbY-Sw3riCueOPxG8rgHs7tEGSr6A&s",
    category: Category.NATURE,
    bgColor: "bg-lime-50",
    textColor: "text-lime-900",
    badgeColor: "bg-lime-200",
    lat: 40.1970,
    lng: 29.0069
  },
  {
    id: 14,
    title: "Trilye & Mudanya",
    description: "Zeytin ağaçları ve denizin buluştuğu sahil kasabaları. Tarihi Rum evleri ve Mütareke Evi ile hem göze hem tarihe hitap eder.",
    imageUrl: "https://www.kusadasitours.com.tr/images/tour/5385_b.jpg",
    category: Category.NATURE,
    bgColor: "bg-blue-100",
    textColor: "text-blue-900",
    badgeColor: "bg-blue-300",
    lat: 40.3923,
    lng: 28.7963
  },
  {
    id: 15,
    title: "Saitabat & Suuçtu Şelaleleri",
    description: "Doğanın serinleten yüzü. Yeşillikler arasından dökülen bu şelaleler, piknikçilerin ve doğa severlerin kaçış noktasıdır.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW5E8ZLDZwcyGJPkqj_S4YXqlXfFepAIK00g&s",
    category: Category.NATURE,
    bgColor: "bg-emerald-100",
    textColor: "text-emerald-900",
    badgeColor: "bg-emerald-300",
    lat: 40.1333,
    lng: 29.2333
  },
  {
    id: 16,
    title: "İskender Kebap",
    description: "Efsanenin doğuşu. Döner eti, tereyağı, domates sosu ve yoğurdun muhteşem uyumu. 1867'den beri Bursa'nın dünyaya hediyesi.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM80C9hfExbitDdxpmqSmpwZBGK-b9wiBUGw&s",
    category: Category.FOOD,
    bgColor: "bg-red-50",
    textColor: "text-red-900",
    badgeColor: "bg-red-200",
    lat: 40.1834,
    lng: 29.0658
  },
  {
    id: 17,
    title: "Pideli Köfte",
    description: "İskender'in kardeşi. Altında pide, üzerinde minik köfteler ve o meşhur tereyağlı sos. Kayhan Çarşısı'nın vazgeçilmez lezzeti.",
    imageUrl: "https://img.ye-mek.net/img/f1/pideli-kofte.jpg",
    category: Category.FOOD,
    bgColor: "bg-orange-100",
    textColor: "text-orange-900",
    badgeColor: "bg-orange-200",
    lat: 40.1848,
    lng: 29.0667
  },
  {
    id: 18,
    title: "İnegöl Köfte",
    description: "Baharatsız lezzet. Balkan göçmenlerinin ustalığıyla şekillenen, sadeliğin ve lezzetin mükemmel dengesi.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoUSnT5iwIHPfYbb6udwcpt8-hsov3VJLY1Q&s",
    category: Category.FOOD,
    bgColor: "bg-amber-100",
    textColor: "text-amber-900",
    badgeColor: "bg-amber-200",
    lat: 40.0782,
    lng: 29.5133
  },
  {
    id: 19,
    title: "Cantık",
    description: "Tatar mutfağının Bursa'ya armağanı. Mayalı hamur üzerine kıyma harcıyla yapılan, pazar sabahlarının vazgeçilmez böreği.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYugLxS0v7iuEC61Vwg2t58UxY7BpxwulkqQ&s",
    category: Category.FOOD,
    bgColor: "bg-yellow-100",
    textColor: "text-yellow-900",
    badgeColor: "bg-yellow-200",
    lat: 40.1830,
    lng: 29.0600
  },
  {
    id: 20,
    title: "Süt Helvası",
    description: "Bursa'nın tatlı sırrı. Fırında üzeri kızartılan, içi akışkan ve sütlü bu hafif tatlı, sadece bu şehre özgü bir lezzet şölenidir.",
    imageUrl: "https://gencgazetenet.teimg.com/crop/1280x720/gencgazete-net/uploads/2024/09/bursanin-en-sevdigi-lezzetlerde-bugun-sut-helvasi-ve-sehrin-tatli-sirri-5.webp",
    category: Category.FOOD,
    bgColor: "bg-cream-50",
    textColor: "text-gray-900",
    badgeColor: "bg-gray-200",
    lat: 40.1840,
    lng: 29.0610
  },
  {
    id: 21,
    title: "Kemalpaşa & Kestane Şekeri",
    description: "Uludağ'ın kestaneleri şekere, Mustafakemalpaşa'nın peyniri tatlıya dönüşür. Bursa'dan dönenlerin elindeki en tatlı hediyeler.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9IK5BnETyd_1ZIuIqCVbi7TLqlQkhB62Rfw&s",
    category: Category.FOOD,
    bgColor: "bg-brown-50",
    textColor: "text-amber-950",
    badgeColor: "bg-amber-300",
    lat: 40.0381,
    lng: 28.4093
  }
];